server:
  port: 8301
spring:
  application:
    name: mall-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native: #本地仓库存储
          search-locations: classpath:/config/{application}
        git: #Git仓库存储
          uri: https://gitee.com/ymtNSN/mall-config.git
          #如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写，
          username:
          password:
          clone-on-start: true
          search-paths: '{application}'
